# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

web:
  replicaCount: 1
  image:
    repository: cloud.canister.io:5000/skoba/ujournal-web
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

modules:
  replicaCount: 1
  image:
    repository: cloud.canister.io:5000/skoba/ujournal-modules
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

nameOverride: ""
fullnameOverride: ""

