FROM node:9-alpine as builder

RUN apk add --update \
    python git build-base

ENV WEB_ROOT /web
RUN mkdir $WEB_ROOT
WORKDIR $WEB_ROOT

COPY . /web

RUN npm install
RUN npm install --global  cross-env

RUN npm run build

# Stage 2
FROM nginx:alpine

RUN apk --update --upgrade add openssl

COPY nginx.conf /etc/nginx/nginx.conf

WORKDIR /usr/share/nginx/html/modules
COPY --from=builder /web/dist/ ./dist
COPY --from=builder /web/index.html ./index.html
