FROM node:9-alpine as builder

RUN apk add --update \
    python git build-base

ENV WEB_ROOT /web
RUN mkdir $WEB_ROOT
WORKDIR $WEB_ROOT

COPY . /web

RUN npm install
RUN npm install --global  cross-env

RUN npm run build

# Stage 2
FROM nginx:alpine

RUN apk --update --upgrade add openssl

WORKDIR /usr/share/nginx/html
COPY --from=builder /web/dist/ .
